/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "DiFX_Delay_Server.h"

bool_t
xdr_DIFX_DELAY_SERVER_vec (XDR *xdrs, DIFX_DELAY_SERVER_vec *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DIFX_DELAY_SERVER_1_station (XDR *xdrs, DIFX_DELAY_SERVER_1_station *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->station_name, DIFX_DELAY_SERVER_STATION_STRING_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->antenna_name, DIFX_DELAY_SERVER_STATION_STRING_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->site_name, DIFX_DELAY_SERVER_STATION_STRING_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->site_ID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->site_type, DIFX_DELAY_SERVER_STATION_STRING_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->axis_type, DIFX_DELAY_SERVER_STATION_STRING_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->station_pos))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->station_vel))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->station_acc))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->station_pointing_dir))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->station_reference_dir))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->station_coord_frame, DIFX_DELAY_SERVER_STATION_STRING_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->pointing_coord_frame, DIFX_DELAY_SERVER_STATION_STRING_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pointing_corrections_applied))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->station_position_delay_offset))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->axis_off))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->primary_axis_wrap))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->secondary_axis_wrap))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->receiver_name, DIFX_DELAY_SERVER_STATION_STRING_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->pressure))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->antenna_pressure))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->temperature))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->wind_speed))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->wind_direction))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->antenna_phys_temperature))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DIFX_DELAY_SERVER_1_source (XDR *xdrs, DIFX_DELAY_SERVER_1_source *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->source_name, DIFX_DELAY_SERVER_STATION_STRING_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->IAU_name, DIFX_DELAY_SERVER_STATION_STRING_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->source_type, DIFX_DELAY_SERVER_STATION_STRING_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->ra))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->dec))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->dra))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->ddec))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->depoch))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->parallax))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->coord_frame, DIFX_DELAY_SERVER_STATION_STRING_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->source_pos))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->source_vel))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->source_acc))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->source_pointing_dir))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->source_pointing_reference_dir))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DIFX_DELAY_SERVER_1_EOP (XDR *xdrs, DIFX_DELAY_SERVER_1_EOP *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->EOP_time))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->tai_utc))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->ut1_utc))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->xpole))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->ypole))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DIFX_DELAY_SERVER_1_RESULTS (XDR *xdrs, DIFX_DELAY_SERVER_1_RESULTS *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->delay))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->dry_atmos))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->wet_atmos))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->iono_atmos))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->az_corr))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->el_corr))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->az_geom))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->el_geom))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->primary_axis_angle))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->secondary_axis_angle))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->mount_source_angle))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->station_antenna_theta))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->station_antenna_phi))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->source_antenna_theta))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->source_antenna_phi))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->UVW))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->baselineP2000))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->baselineV2000))
		 return FALSE;
	 if (!xdr_DIFX_DELAY_SERVER_vec (xdrs, &objp->baselineA2000))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_getDIFX_DELAY_SERVER_1_arg (XDR *xdrs, getDIFX_DELAY_SERVER_1_arg *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (6 + ( NUM_DIFX_DELAY_SERVER_1_KFLAGS )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_long (xdrs, &objp->request_id))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->delay_server))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->server_struct_setup_code))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->date))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->ref_frame))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->verbosity))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->kflags, NUM_DIFX_DELAY_SERVER_1_KFLAGS,
				sizeof (short), (xdrproc_t) xdr_short))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->request_id);
		IXDR_PUT_U_LONG(buf, objp->delay_server);
		IXDR_PUT_LONG(buf, objp->server_struct_setup_code);
		IXDR_PUT_LONG(buf, objp->date);
		IXDR_PUT_LONG(buf, objp->ref_frame);
		IXDR_PUT_LONG(buf, objp->verbosity);
		{
			register short *genp;

			for (i = 0, genp = objp->kflags;
				i < NUM_DIFX_DELAY_SERVER_1_KFLAGS; ++i) {
				IXDR_PUT_SHORT(buf, *genp++);
			}
		}
		}
		 if (!xdr_double (xdrs, &objp->time))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->sky_frequency))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->Use_Server_Station_Table))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->Num_Stations))
			 return FALSE;
		 if (!xdr_array (xdrs, (char **)&objp->station.station_val, (u_int *) &objp->station.station_len, ~0,
			sizeof (DIFX_DELAY_SERVER_1_station), (xdrproc_t) xdr_DIFX_DELAY_SERVER_1_station))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->Use_Server_Source_Table))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->Num_Sources))
			 return FALSE;
		 if (!xdr_array (xdrs, (char **)&objp->source.source_val, (u_int *) &objp->source.source_len, ~0,
			sizeof (DIFX_DELAY_SERVER_1_source), (xdrproc_t) xdr_DIFX_DELAY_SERVER_1_source))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->Use_Server_EOP_Table))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->Num_EOPs))
			 return FALSE;
		 if (!xdr_array (xdrs, (char **)&objp->EOP.EOP_val, (u_int *) &objp->EOP.EOP_len, ~0,
			sizeof (DIFX_DELAY_SERVER_1_EOP), (xdrproc_t) xdr_DIFX_DELAY_SERVER_1_EOP))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (6 + ( NUM_DIFX_DELAY_SERVER_1_KFLAGS )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_long (xdrs, &objp->request_id))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->delay_server))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->server_struct_setup_code))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->date))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->ref_frame))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->verbosity))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->kflags, NUM_DIFX_DELAY_SERVER_1_KFLAGS,
				sizeof (short), (xdrproc_t) xdr_short))
				 return FALSE;

		} else {
		objp->request_id = IXDR_GET_LONG(buf);
		objp->delay_server = IXDR_GET_U_LONG(buf);
		objp->server_struct_setup_code = IXDR_GET_LONG(buf);
		objp->date = IXDR_GET_LONG(buf);
		objp->ref_frame = IXDR_GET_LONG(buf);
		objp->verbosity = IXDR_GET_LONG(buf);
		{
			register short *genp;

			for (i = 0, genp = objp->kflags;
				i < NUM_DIFX_DELAY_SERVER_1_KFLAGS; ++i) {
				*genp++ = IXDR_GET_SHORT(buf);
			}
		}
		}
		 if (!xdr_double (xdrs, &objp->time))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->sky_frequency))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->Use_Server_Station_Table))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->Num_Stations))
			 return FALSE;
		 if (!xdr_array (xdrs, (char **)&objp->station.station_val, (u_int *) &objp->station.station_len, ~0,
			sizeof (DIFX_DELAY_SERVER_1_station), (xdrproc_t) xdr_DIFX_DELAY_SERVER_1_station))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->Use_Server_Source_Table))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->Num_Sources))
			 return FALSE;
		 if (!xdr_array (xdrs, (char **)&objp->source.source_val, (u_int *) &objp->source.source_len, ~0,
			sizeof (DIFX_DELAY_SERVER_1_source), (xdrproc_t) xdr_DIFX_DELAY_SERVER_1_source))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->Use_Server_EOP_Table))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->Num_EOPs))
			 return FALSE;
		 if (!xdr_array (xdrs, (char **)&objp->EOP.EOP_val, (u_int *) &objp->EOP.EOP_len, ~0,
			sizeof (DIFX_DELAY_SERVER_1_EOP), (xdrproc_t) xdr_DIFX_DELAY_SERVER_1_EOP))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_long (xdrs, &objp->request_id))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->delay_server))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->server_struct_setup_code))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->date))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->ref_frame))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->verbosity))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->kflags, NUM_DIFX_DELAY_SERVER_1_KFLAGS,
		sizeof (short), (xdrproc_t) xdr_short))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->time))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->sky_frequency))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Use_Server_Station_Table))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->Num_Stations))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->station.station_val, (u_int *) &objp->station.station_len, ~0,
		sizeof (DIFX_DELAY_SERVER_1_station), (xdrproc_t) xdr_DIFX_DELAY_SERVER_1_station))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Use_Server_Source_Table))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->Num_Sources))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->source.source_val, (u_int *) &objp->source.source_len, ~0,
		sizeof (DIFX_DELAY_SERVER_1_source), (xdrproc_t) xdr_DIFX_DELAY_SERVER_1_source))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Use_Server_EOP_Table))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->Num_EOPs))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->EOP.EOP_val, (u_int *) &objp->EOP.EOP_len, ~0,
		sizeof (DIFX_DELAY_SERVER_1_EOP), (xdrproc_t) xdr_DIFX_DELAY_SERVER_1_EOP))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DIFX_DELAY_SERVER_1_res (XDR *xdrs, DIFX_DELAY_SERVER_1_res *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 8 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->delay_server_error))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->server_error))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->model_error))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->request_id))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->delay_server))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->server_struct_setup_code))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->server_version))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->date))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->delay_server_error);
		IXDR_PUT_LONG(buf, objp->server_error);
		IXDR_PUT_LONG(buf, objp->model_error);
		IXDR_PUT_LONG(buf, objp->request_id);
		IXDR_PUT_U_LONG(buf, objp->delay_server);
		IXDR_PUT_LONG(buf, objp->server_struct_setup_code);
		IXDR_PUT_U_LONG(buf, objp->server_version);
		IXDR_PUT_LONG(buf, objp->date);
		}
		 if (!xdr_double (xdrs, &objp->time))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->Num_Stations))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->Num_Sources))
			 return FALSE;
		 if (!xdr_array (xdrs, (char **)&objp->result.result_val, (u_int *) &objp->result.result_len, ~0,
			sizeof (DIFX_DELAY_SERVER_1_RESULTS), (xdrproc_t) xdr_DIFX_DELAY_SERVER_1_RESULTS))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 8 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->delay_server_error))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->server_error))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->model_error))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->request_id))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->delay_server))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->server_struct_setup_code))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->server_version))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->date))
				 return FALSE;

		} else {
		objp->delay_server_error = IXDR_GET_LONG(buf);
		objp->server_error = IXDR_GET_LONG(buf);
		objp->model_error = IXDR_GET_LONG(buf);
		objp->request_id = IXDR_GET_LONG(buf);
		objp->delay_server = IXDR_GET_U_LONG(buf);
		objp->server_struct_setup_code = IXDR_GET_LONG(buf);
		objp->server_version = IXDR_GET_U_LONG(buf);
		objp->date = IXDR_GET_LONG(buf);
		}
		 if (!xdr_double (xdrs, &objp->time))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->Num_Stations))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->Num_Sources))
			 return FALSE;
		 if (!xdr_array (xdrs, (char **)&objp->result.result_val, (u_int *) &objp->result.result_len, ~0,
			sizeof (DIFX_DELAY_SERVER_1_RESULTS), (xdrproc_t) xdr_DIFX_DELAY_SERVER_1_RESULTS))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->delay_server_error))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->server_error))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->model_error))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->request_id))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->delay_server))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->server_struct_setup_code))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->server_version))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->date))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->time))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->Num_Stations))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->Num_Sources))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->result.result_val, (u_int *) &objp->result.result_len, ~0,
		sizeof (DIFX_DELAY_SERVER_1_RESULTS), (xdrproc_t) xdr_DIFX_DELAY_SERVER_1_RESULTS))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_getDIFX_DELAY_SERVER_PARAMETERS_1_arg (XDR *xdrs, getDIFX_DELAY_SERVER_PARAMETERS_1_arg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_long (xdrs, &objp->request_id))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->delay_server))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->server_struct_setup_code))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->verbosity))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->request_id);
			IXDR_PUT_U_LONG(buf, objp->delay_server);
			IXDR_PUT_LONG(buf, objp->server_struct_setup_code);
			IXDR_PUT_LONG(buf, objp->verbosity);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_long (xdrs, &objp->request_id))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->delay_server))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->server_struct_setup_code))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->verbosity))
				 return FALSE;
		} else {
			objp->request_id = IXDR_GET_LONG(buf);
			objp->delay_server = IXDR_GET_U_LONG(buf);
			objp->server_struct_setup_code = IXDR_GET_LONG(buf);
			objp->verbosity = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_long (xdrs, &objp->request_id))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->delay_server))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->server_struct_setup_code))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->verbosity))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DIFX_DELAY_SERVER_PARAMETERS_1_res (XDR *xdrs, DIFX_DELAY_SERVER_PARAMETERS_1_res *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 7 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->delay_server_error))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->server_error))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->model_error))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->request_id))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->delay_server))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->server_struct_setup_code))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->server_version))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->delay_server_error);
		IXDR_PUT_LONG(buf, objp->server_error);
		IXDR_PUT_LONG(buf, objp->model_error);
		IXDR_PUT_LONG(buf, objp->request_id);
		IXDR_PUT_U_LONG(buf, objp->delay_server);
		IXDR_PUT_LONG(buf, objp->server_struct_setup_code);
		IXDR_PUT_U_LONG(buf, objp->server_version);
		}
		 if (!xdr_double (xdrs, &objp->accelgrv))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->e_flat))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->earthrad))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->mmsems))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->ephepoc))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gauss))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->u_grv_cn))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmsun))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmmercury))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmvenus))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmearth))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmmoon))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmmars))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmjupiter))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmsaturn))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmuranus))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmneptune))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->etidelag))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->love_h))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->love_l))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->pre_data))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->rel_data))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->tidalut1))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->au))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->tsecau))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->vlight))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 7 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->delay_server_error))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->server_error))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->model_error))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->request_id))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->delay_server))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->server_struct_setup_code))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->server_version))
				 return FALSE;

		} else {
		objp->delay_server_error = IXDR_GET_LONG(buf);
		objp->server_error = IXDR_GET_LONG(buf);
		objp->model_error = IXDR_GET_LONG(buf);
		objp->request_id = IXDR_GET_LONG(buf);
		objp->delay_server = IXDR_GET_U_LONG(buf);
		objp->server_struct_setup_code = IXDR_GET_LONG(buf);
		objp->server_version = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_double (xdrs, &objp->accelgrv))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->e_flat))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->earthrad))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->mmsems))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->ephepoc))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gauss))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->u_grv_cn))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmsun))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmmercury))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmvenus))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmearth))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmmoon))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmmars))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmjupiter))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmsaturn))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmuranus))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->gmneptune))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->etidelag))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->love_h))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->love_l))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->pre_data))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->rel_data))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->tidalut1))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->au))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->tsecau))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->vlight))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->delay_server_error))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->server_error))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->model_error))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->request_id))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->delay_server))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->server_struct_setup_code))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->server_version))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->accelgrv))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->e_flat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->earthrad))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->mmsems))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->ephepoc))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->gauss))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->u_grv_cn))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->gmsun))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->gmmercury))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->gmvenus))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->gmearth))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->gmmoon))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->gmmars))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->gmjupiter))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->gmsaturn))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->gmuranus))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->gmneptune))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->etidelag))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->love_h))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->love_l))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->pre_data))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->rel_data))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->tidalut1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->au))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->tsecau))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->vlight))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_getDIFX_DELAY_SERVER_1_res (XDR *xdrs, getDIFX_DELAY_SERVER_1_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->this_error))
		 return FALSE;
	switch (objp->this_error) {
	case 0:
		 if (!xdr_DIFX_DELAY_SERVER_1_res (xdrs, &objp->getDIFX_DELAY_SERVER_1_res_u.response))
			 return FALSE;
		break;
	case 1:
		 if (!xdr_pointer (xdrs, (char **)&objp->getDIFX_DELAY_SERVER_1_res_u.errmsg, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_getDIFX_DELAY_SERVER_PARAMETERS_1_res (XDR *xdrs, getDIFX_DELAY_SERVER_PARAMETERS_1_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->this_error))
		 return FALSE;
	switch (objp->this_error) {
	case 0:
		 if (!xdr_DIFX_DELAY_SERVER_PARAMETERS_1_res (xdrs, &objp->getDIFX_DELAY_SERVER_PARAMETERS_1_res_u.response))
			 return FALSE;
		break;
	case 1:
		 if (!xdr_pointer (xdrs, (char **)&objp->getDIFX_DELAY_SERVER_PARAMETERS_1_res_u.errmsg, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
